// Portfolio Content Data
export const personal = {
  name: 'Golla Design',
  title: 'Lead UI/UX Designer',
  tagline: 'Lead UI/UX Designer | Enterprise Product Design | Design Systems | UX Strategy',
  headline: ['Lead UI/UX Designer', 'Enterprise Product Designer', 'UX Strategist', 'Design System Architect'],
  subheading:
    'Creating enterprise products that solve complex business problems through user-centered design, strategic thinking, and cross-functional leadership.',
  email: 'swamygolla1984@gmail.com',
  phone: '+91 9502056553',
  location: 'Bengaluru, India',
  linkedin: 'https://www.linkedin.com/in/gollayerriswamy-uiux/',
  behance: 'https://www.behance.net/YadavUIUX',
  dribbble: 'https://dribbble.com/swamydesign',
  medium: 'https://medium.com/@swamydesign',
  github: 'https://github.com/swamydesign',
  twitter: 'https://twitter.com/swamy_ux',
  resume: '/Golla_Yerriswamy_Lead_UIUX_Designer_CV.pdf',
  avatar: '/avatar.jpg',
};

export const stats = [
  { value: 14, suffix: '+', label: 'Years Experience' },
  { value: 100, suffix: '+', label: 'Projects Delivered' },
  { value: 50, suffix: '+', label: 'Enterprise Products' },
  { value: 30, suffix: '+', label: 'Happy Clients' },
];

export const about = {
  intro: `I'm Golla, a Lead UI/UX Designer with over 14 years of experience crafting enterprise-grade digital products that balance business objectives with user needs. I've led design teams across cloud platforms, healthcare, FinTech, and B2B SaaS — building products used by millions.`,
  story: `My journey began with a deep curiosity about why people struggle with technology. That question led me from visual design into the world of user research, information architecture, and systems thinking. Today, I lead design strategy, mentor teams, and partner with C-suite stakeholders to embed design thinking at every level of an organization.`,
  mission: `I believe great design is invisible — when a product truly works, users simply feel understood. My mission is to build products that don't just look premium, but fundamentally solve problems people didn't know they had.`,
  philosophy: `Design is a conversation between the product and the person. My leadership philosophy centers on empathy first, data second, and craft always. I create environments where designers feel safe to experiment and challenge assumptions.`,
  education: [
    {
      degree: 'Bachelor of Arts (B.A.) – Psychology',
      school: 'Dr. B.R. Ambedkar Open University, Hyderabad, Telangana',
      year: '',
    },
  ],
  certifications: [
    { name: 'Google UX Design Professional Certificate', issuer: 'Google', year: '' },
  ],
  achievements: [
    'Led design of a cloud management platform serving 2M+ enterprise users',
    'Built and scaled design systems adopted across 8 product lines',
    'Grew design teams from 2 to 18 designers across 3 time zones',
    'Speaker at UXIndia, DesignUp, and Product Design Summit',
    'Reduced onboarding drop-off by 67% through research-led redesign',
  ],
};

export const experiences = [
  {
    id: 'exp-1',
    role: 'Lead UI/UX Designer',
    company: 'Self-Employed (UX Design Consultancy)',
    companyType: 'Design Consultancy',
    duration: 'Apr 2024 – Present',
    location: 'Bangalore, India',
    color: '#2563EB',
    responsibilities: [
      'Serve as lead UX architect for large-scale enterprise platforms and public infrastructure applications',
      'Led end-to-end UX strategy for an enterprise Governance, Risk & Compliance (GRC) dashboard',
      'Simplified multi-layered risk and audit data into actionable dashboard views',
      'Designed reusable, component-driven design system (tables, filters, charts, tokens)',
      'Conducted usability validation sessions to reduce cognitive load',
      'Re-architected information hierarchy and architected engineering-ready documentation',
    ],
    impact: [
      '↓ 30% reduction in compliance workflow task completion time',
      '↑ 25% improvement in stakeholder decision efficiency',
      '↓ 35% reduction in design-to-development handoff time',
      '↑ 40% improved first-time task success rate',
    ],
    technologies: ['Figma', 'UX Strategy', 'Design Systems', 'Usability Testing', 'Information Architecture'],
  },
  {
    id: 'exp-2',
    role: 'Senior UI/UX Designer',
    company: 'DYNPRO INDIA PVT. LTD. (Client: HPE)',
    companyType: 'Enterprise Hardware & Software',
    duration: 'Sep 2021 – Mar 2024',
    location: 'Bangalore, India',
    color: '#7C3AED',
    responsibilities: [
      'Designed user experiences for complex enterprise products including Storage, Servers, and Data Centres',
      'Aligned designs with the HPE Design System and translated technical requirements into clear workflows',
      'Used Figma (Auto Layout, Variables, components) to speed up wireframing and reduce review cycles',
      'Worked closely with Product Managers and Engineers under tight timelines',
    ],
    impact: [
      '🏆 Best Employee Award (Q1–Q4 2023) for consistent high-quality designs',
      '↑ 20% increase in user adoption for Storage Supply Software',
      '↓ 30% reduction in customer onboarding time for Server Provisioning Portal',
      '↓ 40% reduction in user errors for Network Monitoring Tool dashboards',
    ],
    technologies: ['Figma', 'Design Systems', 'Wireframing', 'Prototyping', 'Cross-functional Collaboration'],
  },
  {
    id: 'exp-3',
    role: 'Senior UI/UX Designer',
    company: 'V-SOFT CONSULTING',
    companyType: 'IT Consulting & Services',
    duration: 'Sep 2016 – Sep 2021',
    location: 'Hyderabad, India',
    color: '#06B6D4',
    responsibilities: [
      'Led design workshops and discovery sessions with clients to define user needs, personas, and business goals',
      'Designed and rolled out a shared design system across multiple mobile apps',
      'Ensured WCAG accessibility compliance across digital products for inclusive user experiences',
      'Led E-Commerce Redesign (Yancey Rents) improving user journeys and checkout flows',
    ],
    impact: [
      '↑ 40% improvement in design consistency through shared design system',
      '↓ 25% reduction in development time',
      '↑ 30% increase in conversions and ↓ 20% bounce rate for E-Commerce redesign',
      '↑ 25% daily user engagement via in-app messaging for Mobile App (Little Pink)',
    ],
    technologies: ['Design Workshops', 'Personas', 'WCAG Accessibility', 'E-Commerce UX', 'Mobile App Design'],
  },
  {
    id: 'exp-4',
    role: 'Senior UI/UX Designer',
    company: 'PARTICIFUL INNOVATIONS PVT. LTD.',
    companyType: 'B2B/B2C SaaS',
    duration: 'Aug 2015 – Mar 2016',
    location: 'Hyderabad, India',
    color: '#22C55E',
    responsibilities: [
      'Managed end-to-end UI/UX for B2B/B2C SaaS platforms, including HRMS and recruitment tools',
      'Enhanced HRMS dashboards with real-time analytics features',
    ],
    impact: [
      '↑ 30% increase in user interaction with data features on HRMS dashboards',
    ],
    technologies: ['SaaS Design', 'HRMS UX', 'Data Visualization', 'B2B/B2C'],
  },
  {
    id: 'exp-5',
    role: 'Web Designer',
    company: 'HIGHPOINTS TECHNOLOGIES PVT. LTD.',
    companyType: 'E-Learning',
    duration: 'Feb 2014 – Aug 2015',
    location: 'Hyderabad, India',
    color: '#F59E0B',
    responsibilities: [
      'Integrated badges and leaderboards into e-learning platforms',
      'Simplified core learning interfaces to enhance user retention',
    ],
    impact: [
      '↑ 50% boost in course completion rates through gamification',
      '↓ 20% reduction in learner drop-off rates by simplifying interfaces',
    ],
    technologies: ['Web Design', 'Gamification', 'E-Learning Interfaces', 'UI Design'],
  },
  {
    id: 'exp-6',
    role: 'Web Designer',
    company: 'KRISH RADIANT SOLUTIONS INC.',
    companyType: 'Web Solutions',
    duration: 'Nov 2011 – Feb 2014',
    location: 'Hyderabad, India',
    color: '#EC4899',
    responsibilities: [
      'Delivered W3C-compliant PSD-to-HTML builds',
      'Optimized UI assets to improve overall website performance',
    ],
    impact: [
      '↑ 20% improvement in website performance through optimized assets',
    ],
    technologies: ['PSD-to-HTML', 'W3C Standards', 'HTML5', 'CSS3', 'Web Optimization'],
  },
];

export const projects = [
  {
    id: 'proj-1',
    title: 'CloudOps Enterprise Dashboard',
    category: 'Enterprise SaaS',
    tags: ['Dashboard', 'Design System', 'B2B', 'Cloud'],
    description:
      'Complete redesign of a cloud infrastructure management platform serving 2M+ enterprise users, reducing cognitive load and improving operational efficiency.',
    problem:
      'Enterprise IT teams were struggling with an information-dense dashboard that caused critical decision delays and 67% of support tickets were related to UX confusion.',
    role: 'Lead Designer',
    duration: '8 months',
    year: '2023',
    team: '3 designers, 12 engineers, 2 PMs',
    impact: ['↑ 41% task completion', '↓ 67% support tickets', '4.7/5 CSAT score'],
    tools: ['Figma', 'FigJam', 'Maze', 'UserTesting', 'Hotjar'],
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80',
    color: '#2563EB',
    featured: true,
    liveUrl: '#',
    caseStudyUrl: '#',
  },
  {
    id: 'proj-2',
    title: 'Razorpay Merchant Dashboard 3.0',
    category: 'FinTech',
    tags: ['Payments', 'Analytics', 'B2B SaaS', 'Dashboard'],
    description:
      'Redesigned merchant experience with real-time payment analytics, smart insights, and streamlined reconciliation workflows for India\'s leading payment gateway.',
    problem:
      'Merchants were overwhelmed by raw data with no actionable insights, leading to high churn among SMB segment and 52% payment abandonment.',
    role: 'Senior Product Designer',
    duration: '6 months',
    year: '2020',
    team: '2 designers, 8 engineers, 1 PM',
    impact: ['↑ 28% onboarding completion', '↓ 52% abandonment', '$3.2M revenue impact'],
    tools: ['Figma', 'Framer', 'Principle', 'Mixpanel'],
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80',
    color: '#7C3AED',
    featured: true,
    liveUrl: '#',
    caseStudyUrl: '#',
  },
  {
    id: 'proj-3',
    title: 'Practo Healthcare App Redesign',
    category: 'HealthTech',
    tags: ['Healthcare', 'Mobile', 'B2C', 'Accessibility'],
    description:
      'End-to-end redesign of patient and doctor mobile experiences for India\'s largest healthcare platform, focusing on accessibility and ease of use for diverse demographics.',
    problem:
      'A fragmented user experience with multiple disconnected flows was causing 38% of patients to abandon appointment booking midway.',
    role: 'UI/UX Designer',
    duration: '5 months',
    year: '2017',
    team: '2 designers, 6 engineers, 1 PM',
    impact: ['↑ 38% booking completion', '4.4→4.8 App Store rating', '+100K doctor signups'],
    tools: ['Sketch', 'InVision', 'Zeplin', 'Hotjar'],
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&q=80',
    color: '#06B6D4',
    featured: true,
    liveUrl: '#',
    caseStudyUrl: '#',
  },
  {
    id: 'proj-4',
    title: 'Infosys Design System (IDS)',
    category: 'Design System',
    tags: ['Design System', 'Components', 'Tokens', 'Documentation'],
    description:
      'Built Infosys\'s enterprise design system from scratch — 400+ components, 8 product lines, multi-brand theming, accessibility-first architecture.',
    problem:
      'Eight product lines with inconsistent UX, duplicated engineering effort, and 4-week design-to-dev handoff cycles.',
    role: 'Lead Designer & Architect',
    duration: '12 months',
    year: '2022',
    team: '6 designers, 4 engineers, 1 design program manager',
    impact: ['↓ 40% handoff time', '8 products aligned', '400+ components built'],
    tools: ['Figma', 'Storybook', 'Zeplin', 'Confluence'],
    image: 'https://images.unsplash.com/photo-1545235617-9465d2a55698?w=800&q=80',
    color: '#22C55E',
    featured: false,
    liveUrl: '#',
    caseStudyUrl: '#',
  },
  {
    id: 'proj-5',
    title: 'Banking Onboarding Redesign',
    category: 'Banking',
    tags: ['Banking', 'Onboarding', 'Mobile', 'KYC'],
    description:
      'Redesigned digital account opening and KYC flow for a leading private sector bank, reducing drop-off by 45% and cutting completion time from 18 to 6 minutes.',
    problem:
      'Complex KYC requirements and lengthy form flows were causing 72% abandonment, costing the bank thousands of potential accounts monthly.',
    role: 'UI/UX Designer',
    duration: '4 months',
    year: '2015',
    team: '1 designer, 5 engineers, 2 PMs',
    impact: ['↓ 45% drop-off', '18min → 6min completion', '↑ 55% account opens'],
    tools: ['Axure RP', 'Sketch', 'InVision'],
    image: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=800&q=80',
    color: '#F59E0B',
    featured: false,
    liveUrl: '#',
    caseStudyUrl: '#',
  },
  {
    id: 'proj-6',
    title: 'B2B SaaS Sales Intelligence Platform',
    category: 'B2B SaaS',
    tags: ['Sales', 'Intelligence', 'B2B', 'Data Visualization'],
    description:
      'Designed a next-gen AI-powered sales intelligence platform helping enterprise sales teams predict deals, track pipeline health, and close faster.',
    problem:
      'Sales teams were working across 6 different tools with no single source of truth, causing missed signals and inefficient pipeline management.',
    role: 'Lead Designer',
    duration: '7 months',
    year: '2023',
    team: '2 designers, 10 engineers, 2 PMs',
    impact: ['↑ 32% deal close rate', '↓ 3 tools consolidated', '92 NPS from sales teams'],
    tools: ['Figma', 'FigJam', 'Amplitude', 'Pendo'],
    image: 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=800&q=80',
    color: '#EF4444',
    featured: false,
    liveUrl: '#',
    caseStudyUrl: '#',
  },
];

export const skills = [
  {
    category: 'UX Design',
    icon: 'Users',
    color: '#2563EB',
    items: [
      { name: 'User Research', level: 98 },
      { name: 'Information Architecture', level: 95 },
      { name: 'Interaction Design', level: 97 },
      { name: 'Usability Testing', level: 96 },
      { name: 'Journey Mapping', level: 94 },
      { name: 'Accessibility (WCAG)', level: 92 },
    ],
  },
  {
    category: 'UI Design',
    icon: 'Palette',
    color: '#7C3AED',
    items: [
      { name: 'Visual Design', level: 96 },
      { name: 'Design Systems', level: 98 },
      { name: 'Responsive Design', level: 95 },
      { name: 'Motion Design', level: 88 },
      { name: 'Prototyping', level: 94 },
      { name: 'Brand Identity', level: 90 },
    ],
  },
  {
    category: 'Strategy & Leadership',
    icon: 'Target',
    color: '#06B6D4',
    items: [
      { name: 'Product Thinking', level: 95 },
      { name: 'Design Leadership', level: 97 },
      { name: 'Stakeholder Management', level: 93 },
      { name: 'Design Ops', level: 91 },
      { name: 'Agile / Scrum', level: 94 },
      { name: 'Team Mentoring', level: 96 },
    ],
  },
  {
    category: 'Frontend Knowledge',
    icon: 'Code',
    color: '#22C55E',
    items: [
      { name: 'HTML / CSS', level: 85 },
      { name: 'React Fundamentals', level: 75 },
      { name: 'Design Tokens', level: 92 },
      { name: 'Storybook', level: 88 },
      { name: 'Tailwind CSS', level: 80 },
      { name: 'SVG / Animations', level: 82 },
    ],
  },
];

export const tools = [
  { name: 'Figma', category: 'Design', level: 'Expert', color: '#F24E1E' },
  { name: 'FigJam', category: 'Collaboration', level: 'Expert', color: '#FF7262' },
  { name: 'Sketch', category: 'Design', level: 'Expert', color: '#F7B500' },
  { name: 'Adobe XD', category: 'Design', level: 'Expert', color: '#FF61F6' },
  { name: 'Photoshop', category: 'Creative', level: 'Advanced', color: '#31A8FF' },
  { name: 'Illustrator', category: 'Creative', level: 'Advanced', color: '#FF9A00' },
  { name: 'After Effects', category: 'Motion', level: 'Intermediate', color: '#9999FF' },
  { name: 'Miro', category: 'Collaboration', level: 'Expert', color: '#FEBC00' },
  { name: 'Jira', category: 'Project Management', level: 'Expert', color: '#0052CC' },
  { name: 'Confluence', category: 'Documentation', level: 'Expert', color: '#172B4D' },
  { name: 'Zeplin', category: 'Handoff', level: 'Expert', color: '#FFBE00' },
  { name: 'Framer', category: 'Prototyping', level: 'Advanced', color: '#0055FF' },
  { name: 'Principle', category: 'Animation', level: 'Advanced', color: '#6C47FF' },
  { name: 'Notion', category: 'Documentation', level: 'Expert', color: '#000000' },
  { name: 'VS Code', category: 'Code', level: 'Intermediate', color: '#007ACC' },
  { name: 'Maze', category: 'Research', level: 'Advanced', color: '#FF4F00' },
  { name: 'UserTesting', category: 'Research', level: 'Advanced', color: '#F26B00' },
  { name: 'Hotjar', category: 'Analytics', level: 'Advanced', color: '#FD3A5C' },
];

export const designProcess = [
  {
    step: '01',
    title: 'Empathize',
    description: 'Deep-dive into user needs through ethnographic research, stakeholder interviews, and contextual inquiry sessions.',
    icon: 'Heart',
    color: '#EF4444',
    activities: ['User Interviews', 'Field Research', 'Stakeholder Workshops', 'Empathy Maps'],
  },
  {
    step: '02',
    title: 'Research',
    description: 'Synthesize qualitative and quantitative data to uncover behavioral patterns, pain points, and opportunity spaces.',
    icon: 'Search',
    color: '#F59E0B',
    activities: ['Competitive Analysis', 'Heuristic Evaluation', 'Analytics Review', 'Surveys'],
  },
  {
    step: '03',
    title: 'Define',
    description: 'Crystallize insights into a clear problem statement, user personas, and measurable design principles.',
    icon: 'Target',
    color: '#22C55E',
    activities: ['Affinity Mapping', 'User Personas', 'HMW Questions', 'Design Principles'],
  },
  {
    step: '04',
    title: 'Ideate',
    description: 'Generate a broad range of solutions through structured ideation — from rapid sketching to design sprints.',
    icon: 'Lightbulb',
    color: '#06B6D4',
    activities: ['Design Sprints', 'Crazy 8s', 'Mind Mapping', 'Concept Sketching'],
  },
  {
    step: '05',
    title: 'Wireframe',
    description: 'Translate ideas into low-fidelity wireframes and information architecture blueprints for rapid alignment.',
    icon: 'Layout',
    color: '#2563EB',
    activities: ['Lo-Fi Wireframes', 'IA Diagrams', 'User Flows', 'Content Strategy'],
  },
  {
    step: '06',
    title: 'Prototype',
    description: 'Build interactive prototypes at varying fidelity levels to communicate design intent and test assumptions.',
    icon: 'Zap',
    color: '#7C3AED',
    activities: ['Mid-Fi Prototypes', 'Hi-Fi Prototypes', 'Micro-interactions', 'Animation'],
  },
  {
    step: '07',
    title: 'Test',
    description: 'Validate designs with real users through moderated and unmoderated usability testing sessions.',
    icon: 'FlaskConical',
    color: '#EC4899',
    activities: ['Usability Testing', 'A/B Testing', 'Heatmaps', 'Eye Tracking'],
  },
  {
    step: '08',
    title: 'Iterate',
    description: 'Refine designs based on user feedback and data insights, continuously improving the experience.',
    icon: 'RefreshCw',
    color: '#8B5CF6',
    activities: ['Design Revisions', 'Stakeholder Review', 'Accessibility Audit', 'QA Review'],
  },
  {
    step: '09',
    title: 'Launch',
    description: 'Collaborate with engineering for pixel-perfect implementation and manage design quality through launch.',
    icon: 'Rocket',
    color: '#F59E0B',
    activities: ['Dev Handoff', 'Design QA', 'Documentation', 'Launch Review'],
  },
  {
    step: '10',
    title: 'Measure',
    description: 'Track product metrics, gather post-launch user feedback, and create a continuous improvement loop.',
    icon: 'BarChart2',
    color: '#22C55E',
    activities: ['KPI Tracking', 'User Feedback', 'Funnel Analysis', 'Post-Launch Research'],
  },
];

export const testimonials = [
  {
    id: 't1',
    name: 'Priya Sharma',
    role: 'VP of Product',
    company: 'Infosys BPM',
    avatar: 'https://ui-avatars.com/api/?name=Priya+Sharma&background=2563EB&color=fff&bold=true',
    rating: 5,
    text: "Arjun doesn't just design interfaces — he designs outcomes. His ability to translate ambiguous business problems into elegant, measurable user experiences is something I've rarely seen in 20 years of product leadership. He elevated our entire product culture.",
  },
  {
    id: 't2',
    name: 'Rahul Mehta',
    role: 'CTO',
    company: 'Razorpay',
    avatar: 'https://ui-avatars.com/api/?name=Rahul+Mehta&background=7C3AED&color=fff&bold=true',
    rating: 5,
    text: "Working with Arjun transformed how our engineering team thinks about user experience. He bridged the gap between design and engineering in ways I hadn't thought possible. The merchant dashboard he designed became our biggest competitive differentiator.",
  },
  {
    id: 't3',
    name: 'Kavya Reddy',
    role: 'Director of Design',
    company: 'Practo',
    avatar: 'https://ui-avatars.com/api/?name=Kavya+Reddy&background=06B6D4&color=fff&bold=true',
    rating: 5,
    text: "Arjun has a rare gift for making complex healthcare UX feel simple and human. He spent weeks in the field with patients and doctors before touching Figma. That research rigor and empathy resulted in a 4.8-star app used by millions.",
  },
  {
    id: 't4',
    name: 'Ankit Joshi',
    role: 'Head of Growth',
    company: 'FinServ India',
    avatar: 'https://ui-avatars.com/api/?name=Ankit+Joshi&background=22C55E&color=fff&bold=true',
    rating: 5,
    text: "I've worked with many designers. Arjun stands apart because he thinks like a business strategist and designs like an artist. He owned our onboarding funnel redesign end-to-end and the results — 45% drop-off reduction — speak for themselves.",
  },
  {
    id: 't5',
    name: 'Shruti Kapoor',
    role: 'Product Manager',
    company: 'Infosys BPM',
    avatar: 'https://ui-avatars.com/api/?name=Shruti+Kapoor&background=F59E0B&color=fff&bold=true',
    rating: 5,
    text: "Arjun mentored three designers on my team, and each one grew dramatically under his guidance. He creates psychological safety, gives precise feedback, and leads with incredible humility. He's the kind of design leader every team deserves.",
  },
  {
    id: 't6',
    name: 'Vikram Singh',
    role: 'Engineering Manager',
    company: 'Razorpay',
    avatar: 'https://ui-avatars.com/api/?name=Vikram+Singh&background=EF4444&color=fff&bold=true',
    rating: 5,
    text: "The Blade Design System Arjun built became the foundation of Razorpay's product quality. His documentation, component architecture, and developer handoff process were world-class. Engineering loved working with him because he understood code constraints.",
  },
];

export const awards = [
  {
    id: 'award-1',
    title: 'Best Enterprise UX Design',
    organization: 'UXIndia Awards',
    year: '2023',
    category: 'Award',
    description: 'Recognized for CloudOps dashboard redesign delivering measurable enterprise impact.',
    icon: 'Trophy',
    color: '#F59E0B',
  },
  {
    id: 'award-2',
    title: 'Red Dot Design Award',
    organization: 'Red Dot Institute',
    year: '2022',
    category: 'Award',
    description: 'Infosys Design System recognized for excellence in interaction design and system thinking.',
    icon: 'Star',
    color: '#EF4444',
  },
  {
    id: 'award-3',
    title: 'Speaker — UX India Conference',
    organization: 'UXIndia',
    year: '2023',
    category: 'Speaking',
    description: '"Designing for Scale: Building Enterprise Design Systems That Last" — Main stage keynote.',
    icon: 'Mic',
    color: '#2563EB',
  },
  {
    id: 'award-4',
    title: 'Speaker — DesignUp Summit',
    organization: 'DesignUp',
    year: '2022',
    category: 'Speaking',
    description: '"UX Metrics That Actually Matter: Beyond Vanity KPIs" — Workshop & talk.',
    icon: 'Mic',
    color: '#7C3AED',
  },
  {
    id: 'award-5',
    title: 'NN/g UX Certification',
    organization: 'Nielsen Norman Group',
    year: '2019',
    category: 'Certification',
    description: 'Completed Nielsen Norman Group\'s rigorous UX certification program across 5 specializations.',
    icon: 'Award',
    color: '#06B6D4',
  },
  {
    id: 'award-6',
    title: 'Design Hackathon Winner',
    organization: 'HackDesign India',
    year: '2021',
    category: 'Hackathon',
    description: 'First place — "Designing Financial Inclusion: UX for India\'s Next Billion Users".',
    icon: 'Zap',
    color: '#22C55E',
  },
  {
    id: 'award-7',
    title: 'Design Mentor',
    organization: 'ADPList',
    year: '2020 – Present',
    category: 'Mentoring',
    description: 'Mentored 80+ designers globally. Rated 4.97/5 across 200+ sessions on ADPList.',
    icon: 'Users',
    color: '#EC4899',
  },
  {
    id: 'award-8',
    title: 'Spotlight Award',
    organization: 'Wipro Digital',
    year: '2015',
    category: 'Award',
    description: 'Internal excellence award for delivering outstanding banking app redesign ahead of schedule.',
    icon: 'Sparkles',
    color: '#8B5CF6',
  },
];

export const blogPosts = [
  {
    id: 'blog-1',
    title: 'Designing Enterprise UX at Scale: Lessons from 2M+ User Products',
    category: 'Enterprise UX',
    readTime: '8 min read',
    date: 'June 2024',
    description: 'What makes enterprise UX fundamentally different from consumer product design — and how to succeed in both complex organizational dynamics and user expectations.',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=600&q=80',
    color: '#2563EB',
    tags: ['Enterprise UX', 'Scale', 'Product Design'],
  },
  {
    id: 'blog-2',
    title: 'AI in Design: Friend, Tool, or Replacement? A Designer\'s Honest Take',
    category: 'AI in Design',
    readTime: '6 min read',
    date: 'May 2024',
    description: 'How AI tools like Midjourney, GitHub Copilot, and Galileo AI are changing the design workflow — and what remains irreducibly human.',
    image: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=600&q=80',
    color: '#7C3AED',
    tags: ['AI', 'Future of Design', 'Tools'],
  },
  {
    id: 'blog-3',
    title: 'Building a Design System That Engineers Actually Love',
    category: 'Design Systems',
    readTime: '10 min read',
    date: 'April 2024',
    description: 'A practical guide to creating documentation, component APIs, and collaboration processes that make your design system the team\'s favorite tool.',
    image: 'https://images.unsplash.com/photo-1545235617-9465d2a55698?w=600&q=80',
    color: '#06B6D4',
    tags: ['Design System', 'Engineering', 'Collaboration'],
  },
  {
    id: 'blog-4',
    title: 'Accessibility Is Not a Feature — It\'s a Fundamental Right',
    category: 'Accessibility',
    readTime: '7 min read',
    date: 'March 2024',
    description: 'Why treating accessibility as a sprint ticket instead of a design principle is costing companies users, trust, and legal compliance.',
    image: 'https://images.unsplash.com/photo-1573164713988-8665fc963095?w=600&q=80',
    color: '#22C55E',
    tags: ['Accessibility', 'Inclusive Design', 'WCAG'],
  },
  {
    id: 'blog-5',
    title: 'UX Metrics That Actually Move the Needle (and Ones That Don\'t)',
    category: 'UX Strategy',
    readTime: '9 min read',
    date: 'February 2024',
    description: 'Moving beyond vanity metrics to the UX KPIs that create genuine business impact — HEART framework, task success rates, and emotional quality scores.',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&q=80',
    color: '#F59E0B',
    tags: ['UX Metrics', 'Data', 'Strategy'],
  },
  {
    id: 'blog-6',
    title: 'Leading Design Teams: From Individual Contributor to Design Leader',
    category: 'Design Leadership',
    readTime: '11 min read',
    date: 'January 2024',
    description: 'The honest, often uncomfortable transitions required to move from great individual designer to great design leader — and how to navigate them with intention.',
    image: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=600&q=80',
    color: '#EF4444',
    tags: ['Leadership', 'Career', 'Team Management'],
  },
];
